name: Publish Python Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Match your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run tests
      run: |
        poetry run pytest

    - name: Build the package
      if: success()  # Build only if tests pass
      run: |
        poetry build

    - name: Publish to PyPI
      if: success()  # Publish only if tests pass
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD
